### ISSUE TITLE
Question about mlib

### ISSUE THREAD

**Issue by bob292** [angeladai/spsg#11]
Hello @angeladai ,

First of all, we appreciate your sharing of  the datagen!

However, we ran into some problems with the program: 
1. We found that the TriMesh(https://github.com/niessner/mLib/blob/d416d327e482b92885187f90fcd2a8530344e331/include/core-mesh/triMesh.h) has no function name setHasNormals(https://github.com/angeladai/spsg/blob/8d0dff65480116799cf35499a7f672c2360bec60/datagen/src/Visualizer.cpp#L291) 
2. And the class Vertex（https://github.com/niessner/mLib/blob/d416d327e482b92885187f90fcd2a8530344e331/include/core-mesh/triMesh.h#L16） does not have a three-argument constructor（https://github.com/angeladai/spsg/blob/8d0dff65480116799cf35499a7f672c2360bec60/datagen/src/Visualizer.cpp#L267）

So I suspect we might not be using the same version of mlib.  Could you please also check? 

Thanks,

**Comment by ferbrjan** [comment]
Hello,

Thank you for sharing the datagen project with us!

However, I have exactly the same problem as @bob292. Have you managed to find a solution?

Thnak you,

Jan Ferbr

**Comment by angeladai** [comment]
mLib has been updated with these two minor functions
