### ISSUE TITLE
Sens files to integrate

### ISSUE THREAD

**Issue by bob292** [angeladai/spsg#12]
Hello @angeladai ,

Thanks for update the mLib. But could you please expain a little bit about the sensor files  to integrate in zParametersScanMP.txt， because I couldn't find "mprm7-labels-mpr40.combined.tsv".

Best,
Bob

**Comment by angeladai** [comment]
The data is from the Matterport3D data release, the tsv file is the category tsv as described here: https://github.com/niessner/Matterport/blob/master/data_organization.md
